// Code generated by "stringer -type=Cosa -trimprefix=Cosa"; DO NOT EDIT.

package things

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CosaSilla-0]
	_ = x[CosaMesa-1]
}

const _Cosa_name = "SillaMesa"

var _Cosa_index = [...]uint8{0, 5, 9}

func (i Cosa) String() string {
	if i < 0 || i >= Cosa(len(_Cosa_index)-1) {
		return "Cosa(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cosa_name[_Cosa_index[i]:_Cosa_index[i+1]]
}
